LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

SRC_PATH := ../../Classes

LOCAL_MODULE := game_shared

LOCAL_MODULE_FILENAME := libgame

LOCAL_SRC_FILES := game/main.cpp

LOCAL_SRC_FILES += \
../../Classes/AppDelegate.cpp \
../../Classes/AttributeCalculate/EquipAttribute.cpp \
../../Classes/AttributeCalculate/Itemunitformula.cpp \
../../Classes/AttributeCalculate/MissionAttribute.cpp \
../../Classes/AttributeCalculate/lib_formula.cpp \
../../Classes/BattleScene/AI/AiManager.cpp \
../../Classes/BattleScene/BattleCacheManager.cpp \
../../Classes/BattleScene/BattleLayer.cpp \
../../Classes/BattleScene/BattleLayerBase.cpp \
../../Classes/BattleScene/BattleLogic.cpp \
../../Classes/BattleScene/BattleMap.cpp \
../../Classes/BattleScene/BattleMapUnits.cpp \
../../Classes/BattleScene/BattleSubBGNode.cpp \
../../Classes/BattleScene/BattleUILayer.cpp \
../../Classes/BattleScene/BattleUnitSprite.cpp \
../../Classes/BattleScene/CalculateDamage.cpp \
../../Classes/BattleScene/DropItem.cpp \
../../Classes/BattleScene/EnemyHeroSprite.cpp \
../../Classes/BattleScene/HeroSprite.cpp \
../../Classes/BattleScene/MapCoord.cpp \
../../Classes/BattleScene/MapObject.cpp \
../../Classes/BattleScene/MapObstacle.cpp \
../../Classes/BattleScene/MonsterContainer.cpp \
../../Classes/BattleScene/MonsterSprite.cpp \
../../Classes/BattleScene/PartnerSprite.cpp \
../../Classes/BattleScene/SportLayer.cpp \
../../Classes/BattleScene/SubLayer/ArenaResultLayer.cpp \
../../Classes/BattleScene/SubLayer/CCBPanelCardSelectNew.cpp \
../../Classes/BattleScene/SubLayer/CCBPanelDialSelect.cpp \
../../Classes/BattleScene/SubLayer/CCBPanelFailureGuide.cpp \
../../Classes/BattleScene/SubLayer/CCBPanelFailureNew.cpp \
../../Classes/BattleScene/SubLayer/CCBPanelVictoryNew.cpp \
../../Classes/BattleScene/ThiefSprite.cpp \
../../Classes/BattleScene/ThrowSprite.cpp \
../../Classes/BattleScene/TrapContainer.cpp \
../../Classes/BattleScene/TrapSprite.cpp \
../../Classes/BattleScene/UnitContainer.cpp \
../../Classes/BattleScene/control/AttackedEffectEngine.cpp \
../../Classes/BattleScene/control/BattleCDButton.cpp \
../../Classes/BattleScene/control/BattleUIButton.cpp \
../../Classes/BattleScene/control/BattleUIComponent.cpp \
../../Classes/BattleScene/control/ComboControl.cpp \
../../Classes/BattleScene/control/CountdownLayer.cpp \
../../Classes/BattleScene/control/ThrowEngine.cpp \
../../Classes/BattleScene/control/UiControlLayer.cpp \
../../Classes/CCBDefine.cpp \
../../Classes/Community/Activity/ActivityNode.cpp \
../../Classes/Community/Activity/CCBActivityLayer.cpp \
../../Classes/Community/Arena/CCBArenaRankLayer.cpp \
../../Classes/Community/Arena/CCBArenaReportLayer.cpp \
../../Classes/Community/Arena/CCBSportsLayer.cpp \
../../Classes/Community/Arena/CCBWorShipLayer.cpp \
../../Classes/Community/Arena/HeroRankLayer.cpp \
../../Classes/Community/Bonus/BonusItem.cpp \
../../Classes/Community/Bonus/CCBBonusFrame.cpp \
../../Classes/Community/Bonus/CCBBonusWindow.cpp \
../../Classes/Community/Bonus/CCBBookedItem.cpp \
../../Classes/Community/Bonus/CCBBookedWindow.cpp \
../../Classes/Community/Bonus/CCBDailyWindow.cpp \
../../Classes/Community/Bonus/CCBInviteWindow.cpp \
../../Classes/Community/Bonus/CCBOfflineWindow.cpp \
../../Classes/Community/Box/CCBBoxOpen.cpp \
../../Classes/Community/CCBChatLayer.cpp \
../../Classes/Community/CCBCommunityHeroSprite.cpp \
../../Classes/Community/CCBDiceLayer.cpp \
../../Classes/Community/CCBEnlistScrollItem.cpp \
../../Classes/Community/CCBExpMedicineLayer.cpp \
../../Classes/Community/CCBForceToItem.cpp \
../../Classes/Community/CCBFriendApply.cpp \
../../Classes/Community/CCBFriendBar.cpp \
../../Classes/Community/CCBFriendChatBar.cpp \
../../Classes/Community/CCBFriendLayer.cpp \
../../Classes/Community/CCBGetGuideLayer.cpp \
../../Classes/Community/CCBGoodsItem.cpp \
../../Classes/Community/CCBInForceBatchLayer.cpp \
../../Classes/Community/CCBInForceLayer.cpp \
../../Classes/Community/CCBInForcePartLayer.cpp \
../../Classes/Community/CCBMainPartnerLayer.cpp \
../../Classes/Community/CCBMainPrestigeLayer.cpp \
../../Classes/Community/CCBMainTaskLayer.cpp \
../../Classes/Community/CCBMap.cpp \
../../Classes/Community/CCBNerveDetailNew.cpp \
../../Classes/Community/CCBNerveNewScrollItem.cpp \
../../Classes/Community/CCBNpcShop.cpp \
../../Classes/Community/CCBPanelCommunityPart.cpp \
../../Classes/Community/CCBPrestigeDiceLayer.cpp \
../../Classes/Community/CCBPrestigeTitleCell.cpp \
../../Classes/Community/CCBPrestigeTitleLayer.cpp \
../../Classes/Community/CCBRankingItem.cpp \
../../Classes/Community/CCBSealedWindow.cpp \
../../Classes/Community/CCBSecretShop.cpp \
../../Classes/Community/CCBTodo.cpp \
../../Classes/Community/CCBWantedTaskLayer.cpp \
../../Classes/Community/Chat/CCBChatLayer1.cpp \
../../Classes/Community/Chat/CCBFriendApplyItem.cpp \
../../Classes/Community/Chat/CCBSearchResult.cpp \
../../Classes/Community/CheatLayer.cpp \
../../Classes/Community/CmtHero.cpp \
../../Classes/Community/CmtLayer/CmtBtnLayer.cpp \
../../Classes/Community/CmtMap.cpp \
../../Classes/Community/CmtNpc.cpp \
../../Classes/Community/CmtPlayersData.cpp \
../../Classes/Community/CommunityLayer.cpp \
../../Classes/Community/Control/AwardDetailLayer.cpp \
../../Classes/Community/Control/BagItemButton.cpp \
../../Classes/Community/Control/CCBNerveTip.cpp \
../../Classes/Community/Control/CellButton.cpp \
../../Classes/Community/Control/CommonNoticeNode.cpp \
../../Classes/Community/Control/CommonPanel.cpp \
../../Classes/Community/Control/EnlistScrollView.cpp \
../../Classes/Community/Control/EnlistView.cpp \
../../Classes/Community/Control/EquipmentButton.cpp \
../../Classes/Community/Control/ExpBar.cpp \
../../Classes/Community/Control/ExpBarControl.cpp \
../../Classes/Community/Control/FightPoiControl.cpp \
../../Classes/Community/Control/FindRoadControl.cpp \
../../Classes/Community/Control/FlashButton.cpp \
../../Classes/Community/Control/FlashSprite.cpp \
../../Classes/Community/Control/FloorLayer.cpp \
../../Classes/Community/Control/FloorNode.cpp \
../../Classes/Community/Control/ItemInfoControl.cpp \
../../Classes/Community/Control/LoadingLayer.cpp \
../../Classes/Community/Control/MallItemCell.cpp \
../../Classes/Community/Control/MaterialButton.cpp \
../../Classes/Community/Control/MicroChatControl.cpp \
../../Classes/Community/Control/MissionButton.cpp \
../../Classes/Community/Control/NoticeNode.cpp \
../../Classes/Community/Control/NpcDialog.cpp \
../../Classes/Community/Control/OnlineBonusControl.cpp \
../../Classes/Community/Control/PressedButton.cpp \
../../Classes/Community/Control/ServerStartJudgeNode.cpp \
../../Classes/Community/Control/TaskAwardLayer.cpp \
../../Classes/Community/Control/TaskItemCell.cpp \
../../Classes/Community/Control/VegetablePlot.cpp \
../../Classes/Community/Control/WantedItemCell.cpp \
../../Classes/Community/Control/WareHouse.cpp \
../../Classes/Community/Control/ZQTextLink.cpp \
../../Classes/Community/EquipDetailLayer.cpp \
../../Classes/Community/Equipment/CCBEquipmentTitleLayer.cpp \
../../Classes/Community/Equipment/CCBInsetDiamondPartLayer.cpp \
../../Classes/Community/Equipment/CCBStrengthenPartLayer.cpp \
../../Classes/Community/Equipment/CCBSynthesisDiamondLayer.cpp \
../../Classes/Community/Equipment/CCBUpgradePartLayer.cpp \
../../Classes/Community/Equipment/CCBWashPartLayer.cpp \
../../Classes/Community/Equipment/DiamondBagPanel.cpp \
../../Classes/Community/Equipment/EquipmentPanel.cpp \
../../Classes/Community/FairyLayer.cpp \
../../Classes/Community/Farmland/CCBSeedSythesisLayer.cpp \
../../Classes/Community/FarmlandLayer.cpp \
../../Classes/Community/Friend/CCBBlackListTip.cpp \
../../Classes/Community/Friend/CCBBonusExchange.cpp \
../../Classes/Community/Friend/CCBBonusInvite.cpp \
../../Classes/Community/Friend/CCBBonusInvitePanel.cpp \
../../Classes/Community/Friend/CCBFriendFrame.cpp \
../../Classes/Community/Friend/CCBFriendItem.cpp \
../../Classes/Community/Friend/CCBFriendSelect.cpp \
../../Classes/Community/Friend/CCBFriendTip.cpp \
../../Classes/Community/Friend/CCBFriendTip1.cpp \
../../Classes/Community/Friend/CCBWorldTip.cpp \
../../Classes/Community/FriendInfoLayer.cpp \
../../Classes/Community/Helper/CCBHelperAwardLayer.cpp \
../../Classes/Community/Helper/CCBHelperLayer.cpp \
../../Classes/Community/ImproveTipPanel.cpp \
../../Classes/Community/LuckyDialLayer.cpp \
../../Classes/Community/MallLayer.cpp \
../../Classes/Community/Mission/CCBHardMissionLayer.cpp \
../../Classes/Community/Mission/CCBRaidTimesLayer.cpp \
../../Classes/Community/Mission/CCBRaidsLayer.cpp \
../../Classes/Community/Mission/CCBSelectMissionLayer.cpp \
../../Classes/Community/Mission/EliteBossLayer.cpp \
../../Classes/Community/Mission/RaidManger.cpp \
../../Classes/Community/Mission/RaidsNode.cpp \
../../Classes/Community/MoneyTreeLayer.cpp \
../../Classes/Community/MovieClip.cpp \
../../Classes/Community/NervePanelNew.cpp \
../../Classes/Community/Partner/CCBPartnerEnlistLayer.cpp \
../../Classes/Community/Partner/CCBPartnerEnlistNode.cpp \
../../Classes/Community/Partner/CCBPartnerExchangeLayer.cpp \
../../Classes/Community/Partner/CCBPartnerFriendlyLayer.cpp \
../../Classes/Community/Partner/CCBPartnerInfoLayer.cpp \
../../Classes/Community/Partner/CCBPartnerInheritLayer.cpp \
../../Classes/Community/Partner/CCBPartnerSelectLayer.cpp \
../../Classes/Community/Partner/CCBPartnerSkillLayer.cpp \
../../Classes/Community/Partner/CCBPartnerTipLayer.cpp \
../../Classes/Community/Pot/CCBPotMain.cpp \
../../Classes/Community/Pot/CCBPotPrize.cpp \
../../Classes/Community/Pot/CCBPotPrizeItem.cpp \
../../Classes/Community/Pot/CCBPotPrizeLayer.cpp \
../../Classes/Community/ProgressLayer.cpp \
../../Classes/Community/ProgressLayerNew.cpp \
../../Classes/Community/Recharge/CCBRechargeFirst.cpp \
../../Classes/Community/Recharge/CCBRechargeLayer.cpp \
../../Classes/Community/Recharge/CCBRechargePackage.cpp \
../../Classes/Community/Recharge/CCBRechargeScrollItem.cpp \
../../Classes/Community/Recharge/CCBRechargeTestLayer.cpp \
../../Classes/Community/Recharge/RechargeManger.cpp \
../../Classes/Community/Recharge/RechargePanel.cpp \
../../Classes/Community/Role/CCBBagLayer.cpp \
../../Classes/Community/Role/CCBHeroDetailInfoLayer.cpp \
../../Classes/Community/Role/CCBHeroInfoLayer.cpp \
../../Classes/Community/Role/CCBHeroTrainLayer.cpp \
../../Classes/Community/Role/CCBRoleLayer.cpp \
../../Classes/Community/SettingsLayer.cpp \
../../Classes/Community/Skill/CCBAttackSkillLayer.cpp \
../../Classes/Community/Skill/CCBBuffSkillLayer.cpp \
../../Classes/Community/Skill/CCBSkillLayer.cpp \
../../Classes/Community/Skill/SkillHero.cpp \
../../Classes/Community/Star/CCBStarCalc.cpp \
../../Classes/Community/Star/CCBStarEquip.cpp \
../../Classes/Community/Star/CCBStarQualitySelect.cpp \
../../Classes/Community/Star/CCBStarStoneConvertTips.cpp \
../../Classes/Community/Star/CCBStarStoneConvertTips1.cpp \
../../Classes/Community/Star/CCBStarStoneExchange.cpp \
../../Classes/Community/Star/CCBStarStoneExchangeItem.cpp \
../../Classes/Community/Star/CCBStarStoneUpgradeTips.cpp \
../../Classes/Community/Star/CCBStarStoneUpgradeTips1.cpp \
../../Classes/Community/Star/CCBStarTitle.cpp \
../../Classes/Community/Star/MaskLayer.cpp \
../../Classes/Community/Star/StarBagItem.cpp \
../../Classes/Community/StartServer/CCBDoubleWindow.cpp \
../../Classes/Community/StartServer/CCBOneWindow.cpp \
../../Classes/Community/StartServer/CCBStartFrame.cpp \
../../Classes/Community/StartServer/CCBTargetWindow.cpp \
../../Classes/Community/StartServer/CCBVip6Window.cpp \
../../Classes/Community/SubLayerManager.cpp \
../../Classes/Community/TipsDetailLayer.cpp \
../../Classes/Community/TowerActivityLayer.cpp \
../../Classes/Community/TowerBattleResult.cpp \
../../Classes/Community/VipLayer.cpp \
../../Classes/Community/WorldBoss/BattleSettleInfo.cpp \
../../Classes/Community/WorldBoss/BossBattleResultLayer.cpp \
../../Classes/Community/WorldBoss/BossHpBarControl.cpp \
../../Classes/Community/WorldBoss/WaitingPanel.cpp \
../../Classes/Community/WorldBoss/WorldBossLayer.cpp \
../../Classes/Community/bodyguard/BodyGuardData.cpp \
../../Classes/Community/bodyguard/CCBBodyGuardLayer.cpp \
../../Classes/Community/bodyguard/CCBBodyguardCompleteLayer.cpp \
../../Classes/Community/bodyguard/CCBBodyguardInfoLayer.cpp \
../../Classes/Community/bodyguard/CCBBodyguardPlayerLayer.cpp \
../../Classes/Community/bodyguard/CCBBodyguardReportLayer.cpp \
../../Classes/Community/bodyguard/CCBInterceptLoseLayer.cpp \
../../Classes/Community/bodyguard/CCBInterceptWinLayer.cpp \
../../Classes/Configs/ActivityConf.cpp \
../../Classes/Configs/BattleMissionConf.cpp \
../../Classes/Configs/BattleUnitConf.cpp \
../../Classes/Configs/CommunityConf.cpp \
../../Classes/Configs/EquipUpgradeConf.cpp \
../../Classes/Configs/GameData.cpp \
../../Classes/Configs/GiftItemConf.cpp \
../../Classes/Configs/HelperConf.cpp \
../../Classes/Configs/ItemConf.cpp \
../../Classes/Configs/LVConf.cpp \
../../Classes/Configs/MagicStoreConf.cpp \
../../Classes/Configs/MapUnitConf.cpp \
../../Classes/Configs/MonsterConf.cpp \
../../Classes/Configs/PartnerConf.cpp \
../../Classes/Configs/PartnerUpgradeConf.cpp \
../../Classes/Configs/PrestigeChallengeConf.cpp \
../../Classes/Configs/RoleAttrConf.cpp \
../../Classes/Configs/RoleForceConf.cpp \
../../Classes/Configs/RoleNerveConf.cpp \
../../Classes/Configs/SceneConf.cpp \
../../Classes/Configs/ShopConf.cpp \
../../Classes/Configs/SkillConf.cpp \
../../Classes/Configs/SwapItemConf.cpp \
../../Classes/Configs/TaskConf.cpp \
../../Classes/Configs/ThrowAttackConf.cpp \
../../Classes/Configs/TutorialConf.cpp \
../../Classes/Configs/UnitAIConf.cpp \
../../Classes/Configs/VipConf.cpp \
../../Classes/Configs/XmlEncrypt.cpp \
../../Classes/Controlls/CCBUtils.cpp \
../../Classes/Controlls/CRUtils.cpp \
../../Classes/Controlls/ChatLayer.cpp \
../../Classes/Controlls/FriendRelateTips.cpp \
../../Classes/Controlls/HRichLabelTTF.cpp \
../../Classes/Controlls/ScheduleAction.cpp \
../../Classes/Controlls/ThirdLayer.cpp \
../../Classes/Controlls/Tips/BodyguardInfoTips.cpp \
../../Classes/Controlls/Tips/CommonTips.cpp \
../../Classes/Controlls/Tips/EquipTips.cpp \
../../Classes/Controlls/Tips/GiftTips.cpp \
../../Classes/Controlls/Tips/OnlineTips.cpp \
../../Classes/Controlls/Tips/PartnerTips.cpp \
../../Classes/Controlls/Tips/SkillTips.cpp \
../../Classes/Controlls/Tips/StarStoneUpgradeTips.cpp \
../../Classes/Controlls/Tips/StuffTips.cpp \
../../Classes/Controlls/Tips/XYTips.cpp \
../../Classes/Controlls/TouchLayer.cpp \
../../Classes/Controlls/XYBaseButton.cpp \
../../Classes/Controlls/XYBaseTouchSprite.cpp \
../../Classes/Controlls/XYButton.cpp \
../../Classes/Controlls/XYContainLayer.cpp \
../../Classes/Controlls/XYDownButton.cpp \
../../Classes/Controlls/XYEditBox.cpp \
../../Classes/Controlls/XYGroup.cpp \
../../Classes/Controlls/XYLblButton.cpp \
../../Classes/Controlls/XYLinkLabel.cpp \
../../Classes/Controlls/XYListContainLayer.cpp \
../../Classes/Controlls/XYListScrollView.cpp \
../../Classes/Controlls/XYListView.cpp \
../../Classes/Controlls/XYMenuItemLabel.cpp \
../../Classes/Controlls/XYMessageBox.cpp \
../../Classes/Controlls/XYNumberView.cpp \
../../Classes/Controlls/XYScaleButton.cpp \
../../Classes/Controlls/XYScrollView.cpp \
../../Classes/Controlls/XYSelectButton.cpp \
../../Classes/Controlls/XYToggleButton.cpp \
../../Classes/Controlls/XYTopLayer.cpp \
../../Classes/Controlls/XYTouchSprite.cpp \
../../Classes/Controlls/XYVertScrollView.cpp \
../../Classes/Controlls/XYWaitForConnectLayer.cpp \
../../Classes/GameManager.cpp \
../../Classes/GameScene.cpp \
../../Classes/GlobalDefine.cpp \
../../Classes/LogicManager.cpp \
../../Classes/LoginLayer/CCBBulletinLayer.cpp \
../../Classes/LoginLayer/CCBCreateRoleLayer.cpp \
../../Classes/LoginLayer/CCBLoginLayer.cpp \
../../Classes/LoginLayer/CCBRegistLayer.cpp \
../../Classes/LoginLayer/CCBSelectRoleLayer.cpp \
../../Classes/LoginLayer/CCBSelectServerLayer.cpp \
../../Classes/LoginLayer/CCBStartLayer.cpp \
../../Classes/LoginLayer/CheckResLayer.cpp \
../../Classes/LoginLayer/LoginController.cpp \
../../Classes/LoginLayer/LoginLayer.cpp \
../../Classes/LoginLayer/XYHttpBridge.cpp \
../../Classes/LoginLayer/XYHttpClient.cpp \
../../Classes/LoginLayer/XYHttpLogin.cpp \
../../Classes/LoginLayer/XYHttpUniPay.cpp \
../../Classes/Network/CMDProcessor.cpp \
../../Classes/Network/CSocketUtil.cpp \
../../Classes/Network/DealErrorCode.cpp \
../../Classes/Network/NetworkManager.cpp \
../../Classes/Network/OnlineManager.cpp \
../../Classes/Network/Thread.cpp \
../../Classes/Network/online_cli_proto_cmd.cpp \
../../Classes/PartnersData.cpp \
../../Classes/ResourcesManager/AudioResource.cpp \
../../Classes/ResourcesManager/EffectResource.cpp \
../../Classes/ResourcesManager/NetResourceManager.cpp \
../../Classes/ResourcesManager/ParticleResource.cpp \
../../Classes/ResourcesManager/ResourcesManager.cpp \
../../Classes/ResourcesManager/SpriteFrameManager.cpp \
../../Classes/ResourcesManager/ThrowResource.cpp \
../../Classes/ResourcesManager/UiResources.cpp \
../../Classes/ResourcesManager/UnitResource.cpp \
../../Classes/RoleData.cpp \
../../Classes/ThirdPlatform/ThirdPlatform.cpp \
../../Classes/TimerManager.cpp \
../../Classes/Tutorial/Controls/AssistantControl.cpp \
../../Classes/Tutorial/Controls/BattleTutorial.cpp \
../../Classes/Tutorial/Controls/ControlTips.cpp \
../../Classes/Tutorial/Controls/LaunchTutorial.cpp \
../../Classes/Tutorial/Controls/OperateTutorial.cpp \
../../Classes/Tutorial/Controls/StartTutorialLayer.cpp \
../../Classes/Tutorial/TutorialDefine.cpp \
../../Classes/Tutorial/TutorialManager.cpp \
../../Classes/Tutorial/XYTutorialLayer.cpp \
../../Classes/UserData.cpp \
../../Classes/UserDataEx.cpp \
../../Classes/Utility/AES.cpp \
../../Classes/Utility/CCShake.cpp \
../../Classes/Utility/Clipboard.cpp \
../../Classes/Utility/ColorLabelTTF.cpp \
../../Classes/Utility/ColorLabelTTFLoader.cpp \
../../Classes/Utility/CommonUtility.cpp \
../../Classes/Utility/DictGenerator.cpp \
../../Classes/Utility/DirtyWordManager.cpp \
../../Classes/Utility/GeometryUtility.cpp \
../../Classes/Utility/IOSUtility.cpp \
../../Classes/Utility/LocalLanguage.cpp \
../../Classes/Utility/Lock.cpp \
../../Classes/Utility/ShowMemoryLayer.cpp \
../../Classes/Utility/UtilityAction.cpp \
../../Classes/Utility/XYString.cpp \
../../Classes/Utility/md5.cpp \
../../Classes/Utility/qdes.cpp \
../../Classes/Utility/tools.cpp \
../../Classes/VisibleRect.cpp \
../../Classes/native_jni.cpp \




LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../libs/cocos2dx \
                    $(LOCAL_PATH)/../../libs/cocos2dx/include \
                    $(LOCAL_PATH)/../../libs/cocos2dx/platform/android \
                    $(LOCAL_PATH)/../../libs/cocos2dx/kazmath/include \
                    $(LOCAL_PATH)/../../libs/extensions \
                    $(LOCAL_PATH)/../../libs/CocosDenshion/include

LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../Classes \
                    $(LOCAL_PATH)/../../Classes/AttributeCalculate \
                    $(LOCAL_PATH)/../../Classes/Utility \
                    $(LOCAL_PATH)/../../Classes/Network \
                    $(LOCAL_PATH)/../../Classes/Configs \
                    $(LOCAL_PATH)/../../Classes/ResourcesManager \
                    $(LOCAL_PATH)/../../Classes/Controlls/Tips \
                    $(LOCAL_PATH)/../../Classes/Controlls \
                    $(LOCAL_PATH)/../../Classes/LoginLayer \
                    $(LOCAL_PATH)/../../Classes/Tutorial/Controls \
                    $(LOCAL_PATH)/../../Classes/Tutorial \
                    $(LOCAL_PATH)/../../Classes/Community \
                    $(LOCAL_PATH)/../../Classes/Community/Activity \
                    $(LOCAL_PATH)/../../Classes/Community/Arena \
                    $(LOCAL_PATH)/../../Classes/Community/Friend \
                    $(LOCAL_PATH)/../../Classes/Community/Farmland \
                    $(LOCAL_PATH)/../../Classes/Community/bodyguard \
                    $(LOCAL_PATH)/../../Classes/Community/Bonus \
                    $(LOCAL_PATH)/../../Classes/Community/Chat \
                    $(LOCAL_PATH)/../../Classes/Community/CmtLayer \
                    $(LOCAL_PATH)/../../Classes/Community/Control \
                    $(LOCAL_PATH)/../../Classes/Community/Equipment \
                    $(LOCAL_PATH)/../../Classes/Community/Farmland \
                    $(LOCAL_PATH)/../../Classes/Community/Helper \
                    $(LOCAL_PATH)/../../Classes/Community/Mission \
                    $(LOCAL_PATH)/../../Classes/Community/Partner \
                    $(LOCAL_PATH)/../../Classes/Community/Pot \
                    $(LOCAL_PATH)/../../Classes/Community/Recharge \
                    $(LOCAL_PATH)/../../Classes/Community/Role \
                    $(LOCAL_PATH)/../../Classes/Community/Skill \
                    $(LOCAL_PATH)/../../Classes/Community/Star \
                    $(LOCAL_PATH)/../../Classes/Community/StartServer \
                    $(LOCAL_PATH)/../../Classes/Community/WorldBoss \
                    $(LOCAL_PATH)/../../Classes/Community/Box \
                    $(LOCAL_PATH)/../../Classes/BattleScene/AI \
                    $(LOCAL_PATH)/../../Classes/BattleScene/control \
                    $(LOCAL_PATH)/../../Classes/BattleScene/SubLayer \
                    $(LOCAL_PATH)/../../Classes/BattleScene \
                    $(LOCAL_PATH)/../../Classes/ThirdPlatform \


#LOCAL_LDLIBS := -llog
#LOCAL_STATIC_LIBRARIES += -llibxml2

LOCAL_WHOLE_STATIC_LIBRARIES += cocos2dx_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocosdenshion_static
LOCAL_WHOLE_STATIC_LIBRARIES += chipmunk_static
LOCAL_WHOLE_STATIC_LIBRARIES += websockets_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_extension_static

include $(BUILD_SHARED_LIBRARY)

$(call import-module,cocos2dx)
$(call import-module,cocos2dx/platform/third_party/android/prebuilt/libcurl)
$(call import-module,CocosDenshion/android)
$(call import-module,extensions)
$(call import-module,external/chipmunk)
