//
//  NotificeDefine.h
//  DragonBattle
//
//  Created by zeng xiaolong on 13-6-8.
//
//

#ifndef DragonBattle_NotificeDefine_h
#define DragonBattle_NotificeDefine_h
#include "cocos2d.h"
#include "proto_base.h"
class NotificeObject:public cocos2d::CCObject
{
public:
    static NotificeObject *create()
    {
        NotificeObject *object = new NotificeObject();
        object->autorelease();
        return object;
    }
    static NotificeObject *create(Cmessage* _msg)
    {
        NotificeObject *object = new NotificeObject();
        object->msg = _msg;
        object->autorelease();
        return object;
    }
    Cmessage *msg;
};

#define SETUSERATTR_NOTE "SETUSERATTR_NOTE"//许翔：将下面的NOTE统一，该NOTE提醒的范围包括：银两、经验值、黄金、体力、功力
#define LVCHANGE_NOTE "LVCHANGE_NOTE" //等级改变
#define EXPCHANGE_NOTE "EXPCHANGE_NOTE" //等级改变

#define ATTRBITECHANGE_NOTE "ATTRBITECHANGE_NOTE"//属性变化

#define WEAR_EQUIPMENT_NOTE "WEAR_EQUIPMENT_NOTE"//穿装

#define PUNCH_EQUIPMENT_NOTE "PUNCH_EQUIPMENT_NOTE"         //打孔
#define GET_DIAMOND_COUNT_NOTE "GET_DIAMOND_COUNT_NOTE"     //获取所有宝石数量
#define INLAY_GEM_SUCC_NOTE "INLAY_GEM_SUCC_NOTE"           //成功镶嵌宝石
#define COMPOSE_GEM_SUCC_NOTE "COMPOSE_GEM_SUCC_NOTE"       //合成宝石

#define ENTERFOREGROUND_NOTE    "ENTERFOREGROUND_NOTE"//从后台返回
#define BAGCHANGE_NOTE          "BAGCHANGE_NOTE"
#define BAGEQUIPCHANGE_NOTE     "BAGEQUIPCHANGE_NOTE"//背包变化
#define BAGITEMCHANGE_NOTE      "BAGITEMCHANGE_NOTE"//背包变化
#define BAGSTUFFCHANGE_NOTE     "BAGSTUFFCHANGE_NOTE"//背包变化
#define BAGCARDCHANGE_NOTE      "BAGCARDCHANGE_NOTE"//背包变化
#define EQUIPCHANGE_NOTE        "EQUIPCHANGE_NOTE"//背包变化

#define KEEP_ALIVE_NOTE         "KEEP_ALIVE_NOTE"// 心跳通知
#define EQUIPMENT_STRENGTHEN_NOTE "EQUIPMENT_STRENGTHEN_NOTE"//装备强化
#define EQUIPMENT_STRENGTHEN_SUCC_NOTE "EQUIPMENT_STRENGTHEN_SUCC_NOTE"//装备强化成功
#define NERVE_UPGRADE_SUCC_NOTE "NERVE_UPGRADE_SUCC_NOTE"//经脉升级成功
#define EQUIPMENT_STRENGTHEN_COOL_DOWN_SUCC_NOTE "EQUIPMENT_STRENGTHEN_COOL_DOWN_SUCC_NOTE"//取消装备强化CD成功
#define NERVE_UPGRADE_COOL_DOWN_SUCC_NOTE "NERVE_UPGRADE_COOL_DOWN_SUCC_NOTE"//取消经脉升级CD成功
#define GET_EQUIPMENT_STRENGTHEN_CD_SUCC_NOTE "GET_EQUIPMENT_STRENGTHEN_CD_SUCC_NOTE" //取得装备强化CD成功
#define GET_NERVE_UNGRADE_CD_SUCC_NOTE "GET_NERVE_UNGRADE_CD_SUCC_NOTE" //取得经脉升级CD成功
#define ARENA_CD_SUCC_NOTE "ARENA_CD_SUCC_NOTE" //竞技场取消CD成功

#define EQUIPMENT_UPGRADE_NOTE "EQUIPMENT_UPGRADE_NOTE"//装备进阶
#define EQUIPMENT_UPGRADE_SUCC_NOTE "EQUIPMENT_UPGRADE_SUCC_NOTE"//装备进阶成功
#define EQUIPMENT_ANIMA_NOTE "EQUIPMENT_ANIMA_NOTE"//装备注灵
#define EQUIPMENT_ANIMA_SUCC_NOTE "EQUIPMENT_ANIMA_SUCC_NOTE"//装备注灵成功
#define EQUIPMENT_BATCH_ANIMA_NOTE "EQUIPMENT_BATCH_ANIMA_NOTE"//装备批量注灵
#define EQUIPMENT_WASH_SUCC_NOTE "EQUIPMENT_WASH_SUCC_NOTE"//装备洗练成功
#define EQUIPMENT_CHANGE_NOTE "EQUIPMENT_CHANGE_NOTE"//装备信息发生变化
#define HEROTRAIN_ADD_NOTE "HEROTRAIN_ADD_NOTE"//人物培养值
#define HEROTRAIN_CONFIRM_NOTE "HEROTRAIN_CONFIRM_NOTE"//人物培养成功
#define CMTMAP_REMOVEPLAYER_NOTE "CMTMAP_REMOVEPLAYER_NOTE"//删除主城地图上下线的玩家
//#define CMTMAP_INSERTPLAYER_NOTE "CMTMAP_INSERTPLAYER_NOTE"//新增主城地图上的玩家
#define UPGRADE_FORCE_NOTE  "UPGRADE_FORCE_NOTE"    //炼气成功
#define SWAPCOMPLETE_NOTE "SWAPCOMPLETE_NOTE"//兑换卖成功
#define BALLOTCOMPLETE_NOTE "BALLOTCOMPLETE_NOTE"//卜卦成功
#define BAGSIZECHANGE_NOTE "BAGSIZECHANGE_NOTE"//扩展背包

#define GETSKILLCOMPLETE_NOTE "GETSKILLCOMPLETE_NOTE"//获取技能
#define SKILLCHANGE_NOTE "SKILLCHANGE_NOTE"//技能变化
#define SKILLLOADCOMPLETE_NOTE "SKILLLOADCOMPLETE_NOTE"//技能装载完成
#define SKILL_NEW_OPEN_NOTE "SKILL_NEW_OPEN_NOTE"//开启新技能
#define CHEAT_ITEM_NOTE "CHEAT_ITEM_NOTE"

#define CMTHEROSTOPRUN_NOTE "CMTHEROSTOPRUN_NOTE"//主城英雄停止走动
#define CMT_HERO_START_RUN_NOTE "CMT_HERO_START_RUN_NOTE"

#define RAIDSTATUE "RAIDSTATUE" //带参数 0扫荡结束 1开始扫荡
#define AUTOBATTLESTART_NOTE "AUTOBATTLESTART_NOTE"//开始扫图
#define GETROUNDSBATTLE_NOTE "GETROUNDSBATTLE_NOTE"
#define AUTOBATTLEEND_NOTE "AUTOBATTLEEND_NOTE"//结束扫图
#define SPEEDBATTLE_NOTE "SPEEDBATTLE_NOTE"//加速扫荡
#define BATTLESTART_NOTE "BATTLESTART_NOTE"//进入关卡
#define GETMISSIONCOMPLETE_NOTE "GETMISSIONCOMPLETE_NOTE"//进入关卡

#define BUY_HAMMER_SUCC_NOTE "BUY_HAMMER_SUCC_NOTE"//购买锤子成功
#define GET_BUY_HAMMER_COUNT_TIMES_NOTE "GET_BUY_HAMMER_COUNT_TIMES_NOTE"//购买锤子次数
#define GET_HAMMER_COUNT_NOTE "GET_HAMMER_COUNT_NOTE"//得到锤子数量
#define GET_KEY_COUNT_NOTE "GET_KEY_COUNT_NOTE"//获得钥匙数量
#define GET_MEDICINE_COUNT_NOTE  "GET_MEDICINE_COUNT_NOTE"//获得经验丹数量
#define GET_PILL_COUNT_NOTE "GET_PILL_COUNT_NOTE"   //得到丹药的数量

#define GLOBAL_MESSAGE_UPDATE "GLOBAL_MESSAGE_UPDATE"//得到世界新消息
#define FRIEND_MESSAGE_UPDATE "FRIEND_MESSAGE_UPDATE"//得到好友新消息
#define MESSAGE_NUMBER_UPDATE "MESSAGE_NUMBER_UPDATE"//消息数目更新
#define FRIEND_REQUEST_NOTE "FRIEND_REQUEST_NOTE"//请求加好友消息
#define MESSAGE_RESET_NUM_NOTE "MESSAGE_RESET_NUM_NOTE" 
#define GET_FRIEND_LIST_NOTE "GET_FRIEND_LIST_NOTE"//拉取好友信息
#define GET_USERS_STATUS_NOTE "GET_USERS_STATUS_NOTE" //用户状态 

#define GET_POT_LIST_NOTE "GET_POT_LIST_NOTE"//得到罐子列表
#define UPGRADE_POT_NOTE "UPGRADE_POT_NOTE"//升级罐子
#define GET_POT_BONUS_NOTE "GET_POT_BONUS_NOTE"//得到所砸罐子奖励

#define PARTNER_SKILL_ITEM_NOTE "PARTNER_SKILL_ITEM_NOTE"//获取技能升级材料
#define USE_PARTNER_CARD_NOTE "USE_PARTNER_CARD_NOTE"//使用弟子卡牌
#define SWAP_PARTNER_CARD_NOTE "SWAP_PARTNER_CARD_NOTE"//兑换弟子
#define INHERIT_PARTNER_NOTE "INHERIT_PARTNER_NOTE"//传承弟子
#define GET_EXILE_PARTNERLIST_NOTE "GET_EXILE_PARTNERLIST_NOTE" //放逐弟子列表
#define PARTNER_ONPLAY_NOTE "PARTNER_ONPLAY_NOTE" //弟子上阵
#define PARTNER_OFFPLAYER_NOTE "PARTNER_OFFPLAYER_NOTE" //弟子下阵
#define PARTNER_DROP_NOTE "PARTNER_DROP_NOTE" //弟子放逐
#define PARTNER_RECALL_NOTE "PARTNER_RECALL_NOTE" //弟子召回
#define PARTNER_INHERIT_NOTE "PARTNER_INHERIT_NOTE" //弟子传承成功
#define PARTNER_SKILLUPGRADE_NOTE "PARTNER_SKILLUPGRADE_NOTE" //技能升级
#define PARTNEREATEXP_NOTE   "PARTNEREATEXP_NOTE"       //伙伴吃经验

#define GET_PRESTIGE_TITLE "GET_PRESTIGE_TITLE"     //声望挑战信息
#define GET_PRESTIGE_PRIZE "GET_PRESTIGE_PRIZE"     //获得声望奖励
#define SET_PRESTIGE_CHALLENGE_MISSION "SET_PRESTIGE_CHALLENGE_MISSION" //设置声望挑战的关卡ID
#define GET_PRESTIGE_CHALLENGE_COUNT "GET_PRESTIGE_CHALLENGE_COUNT" //每日声望挑战次数
#define GET_ENERY_COUNT "GET_ENERY_COUNT" //每日购买体力次数
#define GET_AND_BUY_ENERY_COUNT "GET_AND_BUY_ENERY_COUNT" //获取体力并次数
#define PRESTIGE_LOTTERY   "PRESTIGE_LOTTERY"       //摇骰子获得声望

#define RECHARGE_FIRST_BONUS_GET_NOTE "RECHARGE_FIRST_BONUS_GET_NOTE" //首充奖励已领取

#define RAIDTASK_COMPLETELNOTE "RAIDTASK_COMPLETELNOTE" //扫荡任务完成 指向箭头删除

#define GET_MAGIC_STORE_NOTE "GET_MAGIC_STORE_NOTE" //得到神秘商店
#define BUY_MAGIC_ITEM_NOTE "BUY_MAGIC_ITEM_NOTE" //购买神秘物品
#define BUY_NPC_ITEM_NOTE "BUY_NPC_ITEM_NOTE" //购买NPC物品
#define FLUSH_MAGIC_STORE "FLUSH_MAGIC_STORE" //刷新神秘商店

#define GET_PLATFORM_BONUS_NOTE "GET_PLATFORM_BONUS_NOTE" //得到平台奖励
#define LOG_IN_SIGN_IN_NOTE "LOG_IN_SIGN_IN_NOTE" //签到、补签
#define GET_PLATFORM_RAND_BONUS_NOTE "GET_PLATFORM_RAND_BONUS_NOTE" //得到平台奖励,随机值
#define GET_PLATFORM_ONLINE_BONUS_NOTE "GET_PLATFORM_ONLINE_BONUS_NOTE" //在线奖励
#define GET_ACTIVE_DEGREE_NOTE "GET_ACTIVE_DEGREE_NOTE" //活跃度奖励
#define GET_DAILY_VIP_FAKE_NOTE "GET_DAILY_VIP_FAKE_NOTE"//在线时长奖元宝
#define GET_DAILY_VIP_FAKE_EFFECT_NOTE "GET_DAILY_VIP_FAKE_EFFECT_NOTE"//在线时长奖元宝特效显示

#define REFRESH_FRIEND_LIST_NOTE "REFRESH_FRIEND_LIST_NOTE"//刷新好友列表
#define ADD_FRIEND_NOTE "ADD_FRIEND_NOTE"//用户添加好友
#define DEAL_FRIEND_REQUEST_NOTE "DEAL_FRIEND_REQUEST_NOTE"//用户处理好友请求
#define DEL_FRIEND_NOTE "DEL_FRIEND_NOTE"//用户删除好友
#define FIND_USER_FROM_NICK_NOTE "FIND_USER_FROM_NICK_NOTE"//通过nick找到用户基本信息

#define UPDATE_TASK_LIST_NOTE "UPDATE_TASK_LIST_NOTE"//更新任务列表
#define ACCEPT_TASK_COMPLETE_NOTE "ACCEPT_TASK_COMPLETE_NOTE"//接受任务
#define DROP_TASK_COMPLETE_NOTE "DROP_TASK_COMPLETE_NOTE"//放弃任务
#define CURRENT_TASK_NOTE "CURRENT_TASK_NOTE"           //当前任务
#define GET_TASK_AWARD_NOTE "GET_TASK_AWARD_NOTE"//接受任务

#define USER_ACTION_NOTE "USER_ACTION_NOTE"//用户上线、下线、移动等动作
#define POST_TASK_DATA_TUTORIAL "POST_TASK_DATA_TUTORIAL"   //任务完成通知引导
#define POST_LEVEL_DATA_TUTORIAL "POST_LEVEL_DATA_TUTORIAL" //升级通知引导

#define LOG_IN_ERROR "LOG_IN_ERROR"//登陆校验出错
#define REGISTER_ERROR "REGISTER_ERROR"//注册出错
#define CREATE_ROLE_ERROR "CREATE_ROLE_ERROR"//创建角色出错

#define MP_CHANGE_NOTE "MP_CHANGE_NOTE"
#define AI_SKILL_NOTE "AI_SKILL_NOTE"
#define AI_EAT_MED_NOTE "AI_EAT_MED_NOTE"
#define UNITHPCHANGE_NOTE "UNITHPCHANGE_NOTE"//血量变化
#define BATTLEEND_NOTE "BATTLEEND_NOTE"//战斗结束
#define KILLMONSTER_NOTE "KILLMONSTER_NOTE"//任务杀怪数
#define BATTLEWIN_NOTE "BATTLEWIN_NOTE"//战斗胜利
#define BATTLELOST_NOTE "BATTLELOST_NOTE"//战斗失败
#define BATTLEUIVISABLE_NOTE "BATTLEUIVISABLE_NOTE"//显示隐藏战斗ui
#define BATTLETUTORIA_NOTE "BATTLETUTORIA_NOTE"//新手战斗
#define BATTLE_STOP_NOTE "BATTLE_STOP_NOTE" //停止战斗
#define BATTLERECONNECT_NOTE "BATTLERECONNECT_NOTE"//战斗断线从联
#define BATTLE_STATE_CHANGE_NOTE "BATTLE_STATE_CHANGE_NOTE"//战斗结束

#define CHANGEHIDDENPLAYER_NOTE "CHANGEHIDDENPLAYER_NOTE" //隐藏玩家
#define PLATFORMLOADING_NOTE "PLATFORMLOADING_NOTE"

#define GET_WANTED_TASK_LIST "GET_WANTED_TASK_LIST"    //悬赏任务
#define ACCEPT_WANTED_TASK_COMPLETE_NOTE "ACCEPT_WANTED_TASK_COMPLETE_NOTE" //接受悬赏任务
#define UPGRADE_WANTED_TASK_NOTE "UPGRADE_WANTED_TASK_NOTE" //一键满星
#define SET_WANTED_TASK_FINISH_NODE "SET_WANTED_TASK_FINISH_NODE" //一键完成
#define FINISH_WANTED_TASK_NODE "FINISH_WANTED_TASK_NODE"   //领取奖励
#define WANTED_TASK_FINISH_NODE "WANTED_TASK_FINISH_NODE"   //悬赏完成通知
#define HAS_DAILY_NOTE "HAS_DAILY_NOTE"        //是否有日常

#define ADD_TO_BLACKLIST_NOTE "ADD_TO_BLACKLIST_NOTE" //拉入黑名单

#define ANENAINFO_NOTE "ANENAINFO_NOTE"//竞技场信息
#define ARENATOP100_NOTE "ARENATOP100_NOTE"//竞技场top100
#define ARENAFIGHT_NOTE "ARENAFIGHT_NOTE"//竞技场开打
#define ARENAFIGHTOVER_NOTE "ARENAFIGHTOVER_NOTE"//竞技场结束
#define WORSHIP_NOTE "WORSHIP_NOTE"//膜拜成功
#define ARENAFILE_NOTE "ARENAFILE_NOTE"//战报
#define ARENAPRIZE_NOTE "ARENAPRIZE_NOTE"//领奖成功
#define WORSHIPINFO_NOTE "WORSHIPINFO_NOTE"//膜拜信息

#define GET_MALL_GOODS_INFO "GET_MALL_GOODS_INFO" //获取商城商品信息
#define GET_ITEM_COUNT_FROM_SHOP "GET_ITEM_COUNT_FROM_SHOP" //商城中物品用户拥有数量
#define BUY_ITEM_FROM_SHOP_SUCCESS "BUY_ITEM_FROM_SHOP_SUCCESS" //购买成功
#define GET_USER_RANK_NOTE "GET_USER_RANK_NOTE" //获取排名

#define GET_GIFT_BOX_NOTE "GET_GIFT_BOX_NOTE" //个人礼包
#define RECIEVE_GIFT_BOX_NOTE "RECIEVE_GIFT_BOX_NOTE" //接收礼包

#define GET_BOSS_MISSION_NOTE "GET_BOSS_MISSION_NOTE" //获取精英boss进度
#define RESET_BOSS_MISSION_NOTE "RESET_BOSS_MISSION_NOTE"
#define AUTO_BATTLE_BOSS_NOTE "AUTO_BATTLE_BOSS_NOTE" //精英副本扫图
#define GET_MAXMISSIONID_NOTE "GET_MAXMISSIONID_NOTE" //

#define GET_VILLA_INFO_NOTE "GET_VILLA_INFO_NOTE" //获取菜地信息
#define PLANT_SUCCESS_NOTE "PLANT_SUCCESS_NOTE" // 成功种植
#define PLANT_HAVEST_NOTE "PLANT_HAVEST_NOTE" //收获
#define LAND_EXPAND_SUCCESS_NOTE "LAND_EXPAND_SUCCESS_NOTE" //开垦土地
#define SPEED_PLANT_NOTE "SPEED_PLANT_NOTE" //加速成长

#define ACTIVITY_DICE_NOTE "ACTIVITY_DICE_NOTE" //押宝活动
#define ACTIVITY_DICE_COUNT_NOTE "ACTIVITY_DICE_COUNT_NOTE" // 押宝次数

#define GET_TOWER_INFO_NOTE "GET_TOWER_INFO_NOTE" //获取爬塔信息
#define AUTO_TOWER_BATTLE_NOTE "AUTO_TOWER_BATTLE_NOTE" //爬塔自动
#define RESET_TOWER_INFO_NOTE "RESET_TOWER_INFO_NOTE" //重置成功

#define GET_OTHER_USER_NOTE "GET_OTHER_USER_NOTE"   //获取好友信息
#define GET_SHAKE_MONEY_COUNT_NOTE "GET_SHAKE_MONEY_COUNT_NOTE" //摇钱树次数
#define SHAKE_MONEY_TREE_NODE "SHAKE_MONEY_TREE_NODE" //摇钱树
#define GET_VILLA_STATE "GET_VILLA_STATE" //农场状态

#define USER_CHOOSE_HORSE_NOTE "USER_CHOOSE_HORSE_NOTE"//选马
#define USER_REFRESH_HORSE_NOTE "USER_REFRESH_HORSE_NOTE"//刷马
#define USER_GET_ESCORT_INFO_NOTE "USER_GET_ESCORT_INFO_NOTE"//押镖信息
#define USER_GET_ESCORT_USERINFO_NOTE "USER_GET_ESCORT_USERINFO_NOTE"//押镖角色信息
#define USER_GET_ESCORT_COMBATINFO_NOTE "USER_GET_ESCORT_COMBATINFO_NOTE"//押镖战报
#define USER_START_KEAP_HORSE_NOTE "USER_START_KEAP_HORSE_NOTE"//开始拦截
#define USER_END_KEAP_HORSE_NOTE "USER_END_KEAP_HORSE_NOTE"//结束拦截
#define USER_START_ESCORT_NOTE "USER_START_ESCORT_NOTE"//开始运镖
#define LAYER_ESCORT_NOTE "LAYER_ESCORT_NOTE"//通知界面开始运镖
#define LAYER_ADD_HORSE_NOTE "LAYER_ADD_HORSE_NOTE"//新增白马
#define LAYER_REMOVE_HORSE_NOTE "LAYER_REMOVE_HORSE_NOTE"//移除白马
#define USER_ESCORT_EXISTS_GIFT_NOTE "USER_ESCORT_EXISTS_GIFT_NOTE"//运镖有奖励

#define GET_STAR_LIST_NOTE "GET_STAR_LIST_NOTE" //得到占星列表
#define ASTROLOGY_NOTE "ASTROLOGY_NOTE" //占星
#define TRANSFORM_STAR_NOTE "TRANSFORM_STAR_NOTE" //转化单个星石
#define AUTO_TRANSFORM_STAR_NOTE "AUTO_TRANSFORM_STAR_NOTE" //一键转化星石
#define EQUIP_STAR_NOTE "EQUIP_STAR_NOTE" //装备或卸下星石
#define UPGRADE_STAR_NOTE "UPGRADE_STAR_NOTE" //升级星石
#define CALL_ASTROLOGER_NOTE "CALL_ASTROLOGER_NOTE" //召唤占星师
#define REPLACE_STAR_STONE_NOTE "REPLACE_STAR_STONE_NOTE" //替换星石

#define INVITE_INFO_NOTE "INVITE_INFO_NOTE" //邀请好友奖励相关信息

#define GET_ORDER_BILL_NOTE "GET_ORDER_BILL_NOTE"//订单号

#define TUTORIAL_BRING "TUTORIAL_BRING" //携带引导

#define POST_USER_CNT_NOTE "POST_USER_CNT_NOTE" //社区总人数
#define USER_GET_WORLD_BOSS_INFO_NOTE "USER_GET_WORLD_BOSS_INFO_NOTE" //世界BOSS信息
#define USER_WORLD_BOSS_BTL_START_NOTE "USER_WORLD_BOSS_BTL_START_NOTE" //战斗开始
#define USER_WORLD_BOSS_BTL_OVER_NOTE "USER_WORLD_BOSS_BTL_OVER_NOTE"   //战斗结束
#define USER_WORLD_BOSS_OVER_NOTI_NOTE "USER_WORLD_BOSS_OVER_NOTI_NOTE" //世界BOSS结束
#define USER_CHECK_WORLD_BOSS_NOTE "USER_CHECK_WORLD_BOSS_NOTE" //
#define USER_START_WORLD_BOSS_NOTE "USER_START_WORLD_BOSS_NOTE" //开始战斗

#define SHOW_SYTHESIS_VIEW_NOTE "SHOW_SYTHESIS_VIEW_NOTE"

#define USER_GET_ENLIST_PARTNER_NOTE "USER_GET_ENLIST_PARTNER_NOTE" //得到酒馆中弟子的状态
#define USER_TRAIN_PARTNER_FRIENDLY_NOTE "USER_TRAIN_PARTNER_FRIENDLY_NOTE"//培养弟子友好度
#define USER_ENLIST_PARTNER_NOTE    "USER_ENLIST_PARTNER_NOTE"      //招募到弟子
#define USER_BY_INVITE_CODE_NOTE "USER_BY_INVITE_CODE_NOTE" //设置邀请我进来的好友码

#define USER_GET_ALL_BATTLE_PRIZE_NOTE "USER_GET_ALL_BATTLE_PRIZE_NOTE" //获得所有老虎机的奖励
#define USER_GET_ACTIVITY_INFO_NOTE "USER_GET_ACTIVITY_INFO_NOTE" //获取活动信息

#define USER_SYS_MSG_NOTE "USER_SYS_MSG_NOTE"
#define USER_REMOVE_SYS_MSG_NOTE "USER_REMOVE_SYS_MSG_NOTE" 
#define TIPS_REMOVE_NOTE "TIPS_REMOVE_NOTE"
#define USER_FINDROAD_NOTE "USER_FINDROAD_NOTE"//寻路状态 0不寻 1寻
#endif
